
---
- hosts: all
  become: true

  vars: 
    motd: 
      - Ansible managed node by rose
    username:
      - rose12345   

  tasks:
   - name: Message of the day
     ansible.builtin.debug:
       msg:
         - "{{ motd }}"
 
   - name: Creating a new user
     ansible.builtin.user:
        name: "{{ username }}"
        uid: 090402
        createhome: yes
        home: /home/"{{ username }}"
        shell: /bin/bash

   - name: install and update python3 and pip3
     package:
       name:
         - python3
         - python-pip
       state: latest
       update_cache: yes
   
   - name: installing java open-jdk for Ubuntu 
     apt:
       name:
         - openjdk-17-jre
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: installing java open-jdk for CentOS
     yum:
       name:
         - java-11-openjdk 
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"

       
       

